import type { CatalogItem } from "../types";

/**
 * Curated Wedding Guest catalog (v0). 12 items, hand-picked for diversity:
 * - 6 classic-leaning, 5 bold-leaning, 1 either
 * - 9 distinct color families (all values in the `ColorFamily` enum)
 * - 6 distinct silhouettes
 * - 7 matte, 4 soft-sheen, 1 high-shine (the high-shine piece intentionally
 *   carries the "camera caution" story — see `scoreOutfits.ts`)
 *
 * All images are AI-generated product-style photography stored under the
 * frontend's `public/demo/outfits/` (see `imageUrl`, which is a relative
 * path the frontend prefixes with its own base URL).
 */
export const weddingGuestCatalog: CatalogItem[] = [
  {
    id: "classic-navy-midi",
    name: "Classic Navy Midi Dress",
    garmentCategory: "full_body",
    imageUrl: "demo/outfits/classic-navy-midi.jpg",
    colorHex: "#2a2f43",
    priceTier: "mid",
    styleVibe: "classic",
    colorFamily: "navy",
    undertone: "cool",
    fabricFinish: "matte",
    silhouette: "midi_dress",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "bold-emerald-jumpsuit",
    name: "Bold Emerald Tailored Jumpsuit",
    garmentCategory: "full_body",
    imageUrl: "demo/outfits/bold-emerald-jumpsuit.jpg",
    colorHex: "#356658",
    priceTier: "mid",
    styleVibe: "bold",
    colorFamily: "emerald",
    undertone: "cool",
    fabricFinish: "matte",
    silhouette: "jumpsuit",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "soft-sage-slip",
    name: "Soft Sage Slip Dress",
    garmentCategory: "full_body",
    imageUrl: "demo/outfits/soft-sage-slip.jpg",
    colorHex: "#aab6a0",
    priceTier: "mid",
    styleVibe: "classic",
    colorFamily: "sage",
    undertone: "cool",
    fabricFinish: "soft_sheen",
    silhouette: "slip_dress",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "rose-wrap-low",
    name: "Rose Wrap Dress",
    garmentCategory: "full_body",
    imageUrl: "demo/outfits/rose-wrap-low.jpg",
    colorHex: "#cc9292",
    priceTier: "low",
    styleVibe: "classic",
    colorFamily: "rose",
    undertone: "warm",
    fabricFinish: "matte",
    silhouette: "wrap_dress",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "champagne-satin-gown",
    name: "Champagne Satin Gown",
    garmentCategory: "full_body",
    imageUrl: "demo/outfits/champagne-satin-gown.jpg",
    colorHex: "#d4bba5",
    priceTier: "high",
    styleVibe: "classic",
    colorFamily: "champagne",
    undertone: "warm",
    fabricFinish: "high_shine",
    silhouette: "maxi_dress",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "teal-blazer-set",
    name: "Teal Tailored Blazer Set",
    garmentCategory: "full_body",
    imageUrl: "demo/outfits/teal-blazer-set.jpg",
    colorHex: "#22717b",
    priceTier: "high",
    styleVibe: "bold",
    colorFamily: "teal",
    undertone: "cool",
    fabricFinish: "matte",
    silhouette: "blazer_set",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "burgundy-wrap-midi",
    name: "Burgundy Wrap Midi Dress",
    garmentCategory: "full_body",
    imageUrl: "demo/outfits/burgundy-wrap-midi.jpg",
    colorHex: "#5e272c",
    priceTier: "mid",
    styleVibe: "bold",
    colorFamily: "burgundy",
    undertone: "warm",
    fabricFinish: "soft_sheen",
    silhouette: "wrap_dress",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "lavender-slip-dress",
    name: "Lavender Slip Dress",
    garmentCategory: "full_body",
    imageUrl: "demo/outfits/lavender-slip-dress.jpg",
    colorHex: "#d6c3db",
    priceTier: "low",
    styleVibe: "classic",
    colorFamily: "lavender",
    undertone: "cool",
    fabricFinish: "soft_sheen",
    silhouette: "slip_dress",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "black-tailored-jumpsuit",
    name: "Black Tailored Jumpsuit",
    garmentCategory: "full_body",
    imageUrl: "demo/outfits/black-tailored-jumpsuit.jpg",
    colorHex: "#363636",
    priceTier: "high",
    styleVibe: "bold",
    colorFamily: "black",
    undertone: "neutral",
    fabricFinish: "matte",
    silhouette: "jumpsuit",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "sage-blazer-set",
    name: "Sage Tailored Blazer Set",
    garmentCategory: "full_body",
    imageUrl: "demo/outfits/sage-blazer-set.jpg",
    colorHex: "#abaf98",
    priceTier: "low",
    styleVibe: "either",
    colorFamily: "sage",
    undertone: "cool",
    fabricFinish: "matte",
    silhouette: "blazer_set",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "emerald-maxi-dress",
    name: "Emerald Draped Maxi Dress",
    garmentCategory: "full_body",
    imageUrl: "demo/outfits/emerald-maxi-dress.jpg",
    colorHex: "#2c5a4f",
    priceTier: "high",
    styleVibe: "bold",
    colorFamily: "emerald",
    undertone: "cool",
    fabricFinish: "soft_sheen",
    silhouette: "maxi_dress",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "navy-wrap-dress",
    name: "Navy Wrap Dress",
    garmentCategory: "full_body",
    imageUrl: "demo/outfits/navy-wrap-dress.jpg",
    colorHex: "#2e3248",
    priceTier: "low",
    styleVibe: "classic",
    colorFamily: "navy",
    undertone: "cool",
    fabricFinish: "matte",
    silhouette: "wrap_dress",
    occasionTags: ["wedding_guest"],
  },
];
