import type { CatalogItem } from "../types";

/**
 * Curated Wedding Guest catalog. 30 items across four dressing traditions —
 * 12 Western, 6 Indian, 6 East Asian, 6 Middle Eastern — hand-picked for
 * diversity of style vibe, colour family, silhouette and fabric finish.
 *
 * Six per tradition is deliberate: `selectOutfits` shortlists three, so a
 * tradition needs enough spread (warm/cool, light/deep) that the colour
 * engine visibly discriminates rather than simply returning whatever few
 * items exist.
 *
 * Every `colorHex` is *measured* from the product photo by
 * `scripts/place-catalog-garments.ts`, which runs the same extractor the
 * product uses on user uploads — never typed in by eye. Re-run that script
 * after changing any image; do not hand-edit these values.
 *
 * All images are AI-generated product-style photography stored under the
 * frontend's `public/demo/outfits/` (see `imageUrl`, which is a relative
 * path the frontend prefixes with its own base URL).
 */
export const weddingGuestCatalog: CatalogItem[] = [
  {
    id: "classic-navy-midi",
    name: "Classic Navy Midi Dress",
    garmentCategory: "full_body",
    tradition: "western",
    imageUrl: "demo/outfits/classic-navy-midi.jpg",
    colorHex: "#2a2f43",
    styleVibe: "classic",
    colorFamily: "navy",
    undertone: "cool",
    fabricFinish: "matte",
    silhouette: "midi_dress",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "bold-emerald-jumpsuit",
    name: "Bold Emerald Tailored Jumpsuit",
    garmentCategory: "full_body",
    tradition: "western",
    imageUrl: "demo/outfits/bold-emerald-jumpsuit.jpg",
    colorHex: "#356658",
    styleVibe: "bold",
    colorFamily: "emerald",
    undertone: "cool",
    fabricFinish: "matte",
    silhouette: "jumpsuit",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "soft-sage-slip",
    name: "Soft Sage Slip Dress",
    garmentCategory: "full_body",
    tradition: "western",
    imageUrl: "demo/outfits/soft-sage-slip.jpg",
    colorHex: "#aab6a0",
    styleVibe: "classic",
    colorFamily: "sage",
    undertone: "cool",
    fabricFinish: "soft_sheen",
    silhouette: "slip_dress",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "rose-wrap-low",
    name: "Rose Wrap Dress",
    garmentCategory: "full_body",
    tradition: "western",
    imageUrl: "demo/outfits/rose-wrap-low.jpg",
    colorHex: "#cc9292",
    styleVibe: "classic",
    colorFamily: "rose",
    undertone: "warm",
    fabricFinish: "matte",
    silhouette: "wrap_dress",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "champagne-satin-gown",
    name: "Champagne Satin Gown",
    garmentCategory: "full_body",
    tradition: "western",
    imageUrl: "demo/outfits/champagne-satin-gown.jpg",
    colorHex: "#d4bba5",
    styleVibe: "classic",
    colorFamily: "champagne",
    undertone: "warm",
    fabricFinish: "high_shine",
    silhouette: "maxi_dress",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "teal-blazer-set",
    name: "Teal Tailored Blazer Set",
    garmentCategory: "full_body",
    tradition: "western",
    imageUrl: "demo/outfits/teal-blazer-set.jpg",
    colorHex: "#22717b",
    styleVibe: "bold",
    colorFamily: "teal",
    undertone: "cool",
    fabricFinish: "matte",
    silhouette: "blazer_set",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "burgundy-wrap-midi",
    name: "Burgundy Wrap Midi Dress",
    garmentCategory: "full_body",
    tradition: "western",
    imageUrl: "demo/outfits/burgundy-wrap-midi.jpg",
    colorHex: "#5e272c",
    styleVibe: "bold",
    colorFamily: "burgundy",
    undertone: "warm",
    fabricFinish: "soft_sheen",
    silhouette: "wrap_dress",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "lavender-slip-dress",
    name: "Lavender Slip Dress",
    garmentCategory: "full_body",
    tradition: "western",
    imageUrl: "demo/outfits/lavender-slip-dress.jpg",
    colorHex: "#d6c3db",
    styleVibe: "classic",
    colorFamily: "lavender",
    undertone: "cool",
    fabricFinish: "soft_sheen",
    silhouette: "slip_dress",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "black-tailored-jumpsuit",
    name: "Black Tailored Jumpsuit",
    garmentCategory: "full_body",
    tradition: "western",
    imageUrl: "demo/outfits/black-tailored-jumpsuit.jpg",
    colorHex: "#363636",
    styleVibe: "bold",
    colorFamily: "black",
    undertone: "neutral",
    fabricFinish: "matte",
    silhouette: "jumpsuit",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "sage-blazer-set",
    name: "Sage Tailored Blazer Set",
    garmentCategory: "full_body",
    tradition: "western",
    imageUrl: "demo/outfits/sage-blazer-set.jpg",
    colorHex: "#abaf98",
    styleVibe: "either",
    colorFamily: "sage",
    undertone: "cool",
    fabricFinish: "matte",
    silhouette: "blazer_set",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "emerald-maxi-dress",
    name: "Emerald Draped Maxi Dress",
    garmentCategory: "full_body",
    tradition: "western",
    imageUrl: "demo/outfits/emerald-maxi-dress.jpg",
    colorHex: "#2c5a4f",
    styleVibe: "bold",
    colorFamily: "emerald",
    undertone: "cool",
    fabricFinish: "soft_sheen",
    silhouette: "maxi_dress",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "navy-wrap-dress",
    name: "Navy Wrap Dress",
    garmentCategory: "full_body",
    tradition: "western",
    imageUrl: "demo/outfits/navy-wrap-dress.jpg",
    colorHex: "#2e3248",
    styleVibe: "classic",
    colorFamily: "navy",
    undertone: "cool",
    fabricFinish: "matte",
    silhouette: "wrap_dress",
    occasionTags: ["wedding_guest"],
  },

  // --- Indian ---
  {
    id: "classic-teal-saree",
    name: "Teal Zari-Border Silk Saree",
    garmentCategory: "full_body",
    tradition: "indian",
    imageUrl: "demo/outfits/classic-teal-saree.jpg",
    colorHex: "#065464",
    styleVibe: "classic",
    colorFamily: "teal",
    undertone: "cool",
    fabricFinish: "soft_sheen",
    silhouette: "saree",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "bold-coral-lehenga",
    name: "Coral Embroidered Lehenga",
    garmentCategory: "full_body",
    tradition: "indian",
    imageUrl: "demo/outfits/bold-coral-lehenga.jpg",
    colorHex: "#e37e5b",
    styleVibe: "bold",
    colorFamily: "coral",
    undertone: "warm",
    fabricFinish: "soft_sheen",
    silhouette: "lehenga",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "classic-navy-anarkali",
    name: "Navy Floor-Length Anarkali",
    garmentCategory: "full_body",
    tradition: "indian",
    imageUrl: "demo/outfits/classic-navy-anarkali.jpg",
    colorHex: "#1e263c",
    styleVibe: "classic",
    colorFamily: "navy",
    undertone: "cool",
    fabricFinish: "matte",
    silhouette: "anarkali",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "bold-mustard-saree",
    name: "Mustard Silk Saree",
    garmentCategory: "full_body",
    tradition: "indian",
    imageUrl: "demo/outfits/bold-mustard-saree.jpg",
    colorHex: "#ad640b",
    styleVibe: "bold",
    colorFamily: "mustard",
    undertone: "warm",
    fabricFinish: "high_shine",
    silhouette: "saree",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "classic-ivory-lehenga",
    name: "Ivory Pearl-Work Lehenga",
    garmentCategory: "full_body",
    tradition: "indian",
    imageUrl: "demo/outfits/classic-ivory-lehenga.jpg",
    colorHex: "#b3aa9d",
    styleVibe: "classic",
    colorFamily: "ivory",
    undertone: "neutral",
    fabricFinish: "high_shine",
    silhouette: "lehenga",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "bold-emerald-sharara",
    name: "Emerald Sharara Set",
    garmentCategory: "full_body",
    tradition: "indian",
    imageUrl: "demo/outfits/bold-emerald-sharara.jpg",
    colorHex: "#143d2d",
    styleVibe: "bold",
    colorFamily: "emerald",
    undertone: "cool",
    fabricFinish: "matte",
    silhouette: "sharara",
    occasionTags: ["wedding_guest"],
  },

  // --- East Asian ---
  {
    id: "bold-burgundy-qipao",
    name: "Burgundy Silk Qipao",
    garmentCategory: "full_body",
    tradition: "east_asian",
    imageUrl: "demo/outfits/bold-burgundy-qipao.jpg",
    colorHex: "#661927",
    styleVibe: "bold",
    colorFamily: "burgundy",
    undertone: "warm",
    fabricFinish: "high_shine",
    silhouette: "qipao",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "classic-blush-hanbok",
    name: "Blush Hanbok",
    garmentCategory: "full_body",
    tradition: "east_asian",
    imageUrl: "demo/outfits/classic-blush-hanbok.jpg",
    colorHex: "#dbb4b0",
    styleVibe: "classic",
    colorFamily: "rose",
    undertone: "warm",
    fabricFinish: "soft_sheen",
    silhouette: "hanbok",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "soft-jade-qipao",
    name: "Jade Cloud-Weave Qipao",
    garmentCategory: "full_body",
    tradition: "east_asian",
    imageUrl: "demo/outfits/soft-jade-qipao.jpg",
    colorHex: "#8ca28e",
    styleVibe: "either",
    colorFamily: "sage",
    undertone: "cool",
    fabricFinish: "matte",
    silhouette: "qipao",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "classic-champagne-aodai",
    name: "Champagne Ao Dai",
    garmentCategory: "full_body",
    tradition: "east_asian",
    imageUrl: "demo/outfits/classic-champagne-aodai.jpg",
    colorHex: "#cfaf7e",
    styleVibe: "classic",
    colorFamily: "champagne",
    undertone: "warm",
    fabricFinish: "soft_sheen",
    silhouette: "ao_dai",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "bold-indigo-hanbok",
    name: "Indigo Hanbok",
    garmentCategory: "full_body",
    tradition: "east_asian",
    imageUrl: "demo/outfits/bold-indigo-hanbok.jpg",
    colorHex: "#21243a",
    styleVibe: "bold",
    colorFamily: "navy",
    undertone: "cool",
    fabricFinish: "matte",
    silhouette: "hanbok",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "classic-blush-qipao",
    name: "Blush Satin Qipao",
    garmentCategory: "full_body",
    tradition: "east_asian",
    imageUrl: "demo/outfits/classic-blush-qipao.jpg",
    colorHex: "#c8adaa",
    styleVibe: "classic",
    colorFamily: "rose",
    undertone: "warm",
    fabricFinish: "soft_sheen",
    silhouette: "qipao",
    occasionTags: ["wedding_guest"],
  },

  // --- Middle Eastern ---
  {
    id: "classic-champagne-abaya",
    name: "Champagne Embellished Abaya",
    garmentCategory: "full_body",
    tradition: "middle_eastern",
    imageUrl: "demo/outfits/classic-champagne-abaya.jpg",
    colorHex: "#caab90",
    styleVibe: "classic",
    colorFamily: "champagne",
    undertone: "warm",
    fabricFinish: "soft_sheen",
    silhouette: "abaya",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "bold-emerald-kaftan",
    name: "Emerald Flowing Kaftan",
    garmentCategory: "full_body",
    tradition: "middle_eastern",
    imageUrl: "demo/outfits/bold-emerald-kaftan.jpg",
    colorHex: "#103c30",
    styleVibe: "bold",
    colorFamily: "emerald",
    undertone: "cool",
    fabricFinish: "matte",
    silhouette: "kaftan",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "classic-rose-abaya",
    name: "Dusty Rose Abaya",
    garmentCategory: "full_body",
    tradition: "middle_eastern",
    imageUrl: "demo/outfits/classic-rose-abaya.jpg",
    colorHex: "#b08286",
    styleVibe: "classic",
    colorFamily: "rose",
    undertone: "warm",
    fabricFinish: "matte",
    silhouette: "abaya",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "classic-navy-kaftan",
    name: "Navy Beaded Kaftan",
    garmentCategory: "full_body",
    tradition: "middle_eastern",
    imageUrl: "demo/outfits/classic-navy-kaftan.jpg",
    colorHex: "#1a1f31",
    styleVibe: "classic",
    colorFamily: "navy",
    undertone: "cool",
    fabricFinish: "matte",
    silhouette: "kaftan",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "bold-terracotta-abaya",
    name: "Terracotta Abaya",
    garmentCategory: "full_body",
    tradition: "middle_eastern",
    imageUrl: "demo/outfits/bold-terracotta-abaya.jpg",
    colorHex: "#ac5f48",
    styleVibe: "bold",
    colorFamily: "terracotta",
    undertone: "warm",
    fabricFinish: "matte",
    silhouette: "abaya",
    occasionTags: ["wedding_guest"],
  },
  {
    id: "classic-lilac-kaftan",
    name: "Lilac Chiffon Kaftan",
    garmentCategory: "full_body",
    tradition: "middle_eastern",
    imageUrl: "demo/outfits/classic-lilac-kaftan.jpg",
    colorHex: "#bdaec6",
    styleVibe: "classic",
    colorFamily: "lavender",
    undertone: "cool",
    fabricFinish: "soft_sheen",
    silhouette: "kaftan",
    occasionTags: ["wedding_guest"],
  },
];
